### ISSUE TITLE
backport k-modal PR 80 to 2024.1

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/ui#100]
PR 80 https://github.com/kytos-ng/ui/pull/80

Related to both:

- <s>https://github.com/kytos-ng/ui/issues/96</s>
- https://github.com/kytos-ng/ui/issues/97

These ones are being asked to be backported, but `k-modal` has only been introduced in development/master so far, so it'd need to be backported too. 

cc'ing @italovalcy

**Comment by italovalcy** [comment]
Hi @viniarck for 2024.1 indeed back porting k-modal would be a good option, for 2023.2 I think it is better to use the old approach and define the modal on the interfaceInfo component directly, because it seems like the new modal rely on some event update that was introduced on Vue3. I'm saying this because I backported it to 2023.1 and leveraged the new component to implement this, but it failed with error of missing "showModal" props (?) -- which I couldn't narrow to the original cause.

**Comment by viniarck** [comment]
> Hi @viniarck for 2024.1 indeed back porting k-modal would be a good option, for 2023.2 I think it is better to use the old approach and define the modal on the interfaceInfo component directly, because it seems like the new modal rely on some event update that was introduced on Vue3. I'm saying this because I backported it to 2023.1 and leveraged the new component to implement this, but it failed with error of missing "showModal" props (?) -- which I couldn't narrow to the original cause.

Got it. Yes, sounds good. Let's go for the least resistance path here on 2023.2, and only backport on 2024.1. Thanks, Italo.

**Comment by italovalcy** [comment]
Hi @viniarck 
> Got it. Yes, sounds good. Let's go for the least resistance path here on 2023.2, and only backport on 2024.1. Thanks, Italo.

After reassessing the situation, it found easier to backport into 2024.1 without using the k-model new component. The reason is that: the switch confirmation implemented on 2024.1 was already using the old style (https://github.com/kytos-ng/topology/blob/10fad8fb291ebfb38a08bd41e8a3539f1dc5123e/ui/k-info-panel/switch_info.kytos#L36-L60). I've just submitted PR #104 using the old style.

Please let me know if we can just close this issue without backporting the k-modal component.
